### ISSUE TITLE
hook not executed

### ISSUE THREAD

**Issue by tabearu** [hyiso/husky#6]
Hey there, 
first of all, I really love your project. Makes working in teams so much easier.

I've run into some difficulties with `commit-msg` hook and I can't figure out what's going wrong. Me and my colleague are both working on the same repository. I added your integration and two hooks `pre-commit` and `commit-msg`. We initialized it with
```sh
flutter pub get # or dart pub get
flutter pub run husky install # or dart run husky install
```
When I commit only the `pre-commit` hook runs, however when my colleague commits both hooks run. Any idea what could cause this?

**Comment by hyiso** [comment]
Sorry for late.
It's difficult to tell what the problem is with the given information above, maybe you can provide more information about your project, the Flutter SDK and the hook script content.

Also, a small reproducible project example would help a lot.

**Comment by tabearu** [comment]
Thanks for the reply. Here's the SDK informations:
```sh
Flutter 3.7.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9944297138 (5 months ago) • 2023-02-08 15:46:04 -0800
Engine • revision 248290d6d5
Tools • Dart 2.19.2 • DevTools 2.20.1
```
For the project:
```sh
environment:
  sdk: ">=2.17.6 <3.0.0"
  <...>
  husky: ^0.1.6
```
I tried commiting with  VSCode, Android Studio and terminal but it doesn't make a difference. I've tested the hook with different tasks but it also doesn't change anything,. Currently the hook looks like this:
```sh
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "test"
```
The project itself doesn't contain a lot of code as we just started with development. It's basically just a few models and one class with the default project/ui still intact. I'm not even sure how to reproduce this as this problem is only appearing on my computer and not on my colleagues.

**Comment by hyiso** [comment]
Is there any output during the committing process?

Also, make sure that the commit-msg is executable.

**Comment by tabearu** [comment]
The only output is:
```sh
 git commit -m "some commit msg"
Pre-Commit Hook finished
[basic-models bfd6754] some commit msg
 1 file changed, 33 insertions(+)
```
Hook is also executable

**Comment by hyiso** [comment]
How about uninstall husky and reinstall it?
```bash
dart run husky uninstall
dart run husky install
```

**Comment by tabearu** [comment]
Just checked and this worked. Thanks a lot!
For anyone else running into this issue: I've previously tried it with
```sh
flutter run husky uninstall
flutter  run husky install
```
but the key seems to be using `dart` instead of `flutter`.
